### ISSUE TITLE
Piecewise function

### ISSUE THREAD

**Issue by aidinbii** [AMICI-dev/AMICI#2454]
Hello, I want to ask whether the piecewise function is working correctly
Because in my simulations it's behaving not as I'm expecting

Example of, how I'm using it:
```
functions:
    - functionId: antigen
      arguments: x
      formula: piecewise(0.02 * x, (x >= 100) && (x <= 150), 1, x > 150, 0)

odes:
    - stateId: mu_4
      rightHandSide: 1*(k_pDC_Antigen_f * mu_1 *antigen(t)) - 1*(k_pDC_d * mu_4)
      initialValue: 10

    - stateId: antigen_state
      rightHandSide: antigen(t) 
      initialValue: 0
    ...
    ...
```
![M82_simulation_states_inner_MODE_AntigenState](https://github.com/AMICI-dev/AMICI/assets/43513377/45461441-98e7-4883-ae6e-49d260e1c785)

Thanks
