### ISSUE TITLE
AMICI does not handle `sympy.core.numbers.ComplexInfinity`

### ISSUE THREAD

**Issue by johannahaffner** [AMICI-dev/AMICI#2791]
Hi! 

I'm just getting started with Amici, apologies if this question is very basic. I'm getting this error, having added a piecewise linear function to the YAML definition of my model 

```bash
PrintMethodNotImplementedError: Unsupported by <class 'amici.cxxcodeprinter.AmiciCxxCodePrinter'>: <class 'sympy.core.numbers.ComplexInfinity'>
Set the printer option 'strict' to False in order to generate partially printed code.
```

I don't mind not being able to print at this step - I would however like to verify if the model I defined is also runnable. I took a look at the documentation (but did not comb through everything). 

A simple enhancement would be to add a sentence to the error message that indicates how one should do what it suggests. I'm happy to do so and can submit a PR to that effect.

**Comment by johannahaffner** [comment]
HI Daniel, thanks for the quick reply! 

The following code reproduces the error in `dweindl/amici:latest`: 

```python
import yaml2sbml
import amici

yaml_file = 'model_specification.yml'
yaml2sbml.validate_yaml(yaml_dir=yaml_file)

sbml_output_file = 'Mup1.xml'
yaml2sbml.yaml2sbml(yaml_file, sbml_output_file)

model_name = 'Mup1'
model_output_dir = 'amici_model'

sbml_importer = amici.SbmlImporter(sbml_output_file)
sbml_importer.sbml2amici(model_name, model_output_dir)
```

The following YAML file causes the failure since I changed `u_in` to be a stepwise function of `t`. Before, `u_in` was a parameter and things worked fine.

```yaml
time:
  variable: t

functions: 
  - functionId: u_in  # Modification with respect to original model: u(t) is a piecewise function
    arguments: t
    formula: piecewise(1, t < 0, 0)

  - functionId: u_P
    arguments: T_P, t
    formula: u_in(t) + (1 - u_in(t)) * exp(-ln(2)/T_P * t)  # no white space in ratio

  - functionId: u_E
    arguments: T_E, t, alpha_E
    formula: alpha_E + (1 - alpha_E) * (1 - u_in(t)) * (1 - exp(-ln(2)/T_E * t))   

  - functionId: v_P
    arguments: k_4, V_C, T_P, t
    formula: k_4 * V_C * u_P(u_in(t), T_P, t)

  - functionId: alpha_M2
    arguments: k_2, I_M, B_BETA, k_M
    formula: k_2 * (1 - I_M^B_BETA)/(k_M^B_BETA + I_M^B_BETA)

  - functionId: mu_E
    arguments: k_1, N_C, T_E, t, alpha_E
    formula: k_1 * N_C * u_E(u_in(t), T_E, t, alpha_E)

  - functionId: v_E
    arguments: V_EM, I_M, k_1, N_C, T_E, t, alpha_E
    formula: V_EM * I_M * mu_E(k_1, N_C, u_in(t), T_E, t, alpha_E)

odes:
  - stateId: V_C
    rightHandSide: mu_C * V_C
    initialValue: V_C00

  - stateId: V_M
    rightHandSide: mu_M * V_M
    initialValue: V_M00

  - stateId: I_C
    rightHandSide: v_P(k_4, V_C, T_P, t)/V_C - k_3 * (I_C - I_M * V_M/V_C) - mu_C * I_C
    initialValue: I_C00

  - stateId: I_M
    rightHandSide: -v_E(V_EM, I_M, k_1, N_C, T_E, t, alpha_E)/V_M + alpha_R * k_5 * n_E/V_M + alpha_M2(k_2, I_M, B_BETA, k_M) * (I_C * V_C - I_M * V_M - n_E)/V_M - mu_M * I_M
    initialValue: I_M00

  - stateId: N_E
    rightHandSide: k_1 * N_C * u_E(T_E, t, alpha_E) - (k_5 + k_3) * N_E
    initialValue: N_E00

  - stateId: n_E
    rightHandSide: v_E(V_EM, I_M, k_1, N_C, T_E, t, alpha_E) - (k_5 + k_3) * n_E
    initialValue: n_E00

parameters:

  - parameterId: k_2
    nominalValue: 0.007986521265955502  # exp(-4.83)
    #lowerBound: -20.72
    #upperBound: 4.61

  - parameterId: k_3
    nominalValue: 0.12123796643338168  # exp(-2.11)
    #lowerBound: -20.72
    #upperBound: 4.61

  - parameterId: k_4
    nominalValue: 0.06653680671501686  # exp(-2.71)
    #lowerBound: -20.72
    #upperBound: 4.61

  - parameterId: k_5
    nominalValue: 0.15107180883637086  # exp(-1.89)
    #lowerBound: -20.72
    #upperBound: 4.61

  - parameterId: k_M
    nominalValue: 0.3166367693790533  # exp(-1.15)
    #lowerBound: -20.72
    #upperBound: 2.3

  - parameterId: alpha_R
    nominalValue: 0.6770568744981647  # exp(-0.39)
    #lowerBound: -20.72
    #upperBound: 0

  - parameterId: T_P
    nominalValue: 36.966052814822504  # exp(3.61)
    #lowerBound: 0
    #upperBound: 5.3

  - parameterId: T_E
    nominalValue: 8.846306258720883  # exp(2.18)
    #lowerBound: 0
    #upperBound: 5.3

  - parameterId: alpha_E
    nominalValue: 0.024723526470339388  # exp(-3.70)
    #lowerBound: -20.72
    #upperBound: 0

  - parameterId: mu_C
    nominalValue: 0.0022428677194858034  # exp(-6.10)
    #lowerBound: -13.82
    #upperBound: -2.3

  - parameterId: mu_M
    nominalValue: 0.0017643022368343355  # exp(-6.34)
    #lowerBound: -13.82
    #upperBound: -2.3

  - parameterId: V_EM
    nominalValue: 6.8209584692907494  # exp(1.92)
    #lowerBound: 0
    #upperBound: 6.91

  - parameterId: V_EC
    nominalValue: 111.05215990569917  # exp(4.71)
    #lowerBound: 0
    #upperBound: 6.21

  - parameterId: D_DELTA
    nominalValue: 2.0339912586467506  # exp(0.71)
    #lowerBound: 0
    #upperBound: 6.91

  - parameterId: V_C00
    nominalValue: 8604.150654023859  # exp(9.06)
    #lowerBound: 6.68
    #upperBound: 18.42

  - parameterId: V_M00
    nominalValue: 4230.180743130794  # exp(8.35)
    #lowerBound: 6.68
    #upperBound: 18.42

  - parameterId: I_C00
    nominalValue: 1.26
    #lowerBound: 0
    #upperBound: 3

  - parameterId: I_M00
    nominalValue: 1.10
    #lowerBound: 0
    #upperBound: 3

  - parameterId: N_C
    nominalValue: 3
  
  - parameterId: B_BETA
    nominalValue: 4

  - parameterId: G_GAMMA
    nominalValue: 8

  - parameterId: k_1
    nominalValue: 8.41

  - parameterId: N_E00
    nominalValue: 0

  - parameterId: n_E00
    nominalValue: 0

  - parameterId: t_m
    nominalValue: 0
```
